/**
 * Stage 4 diff helpers.
 *
 * The actual diff summary is generated by Claude (see assembleDiffPrompt),
 * but we also compute simple local metrics (length delta, edit distance
 * rough estimate) so the UI can show something immediately without waiting
 * for the API call.
 */

export interface LocalDiffMetrics {
  first_draft_word_count: number;
  final_word_count: number;
  word_delta: number;
  word_delta_pct: number;
}

function wordCount(s: string): number {
  return s.trim().split(/\s+/).filter(Boolean).length;
}

export function computeLocalDiffMetrics(
  firstDraft: string,
  finalDraft: string,
): LocalDiffMetrics {
  const fd = wordCount(firstDraft);
  const fin = wordCount(finalDraft);
  const delta = fin - fd;
  const pct = fd === 0 ? 0 : Math.round((delta / fd) * 100);
  return {
    first_draft_word_count: fd,
    final_word_count: fin,
    word_delta: delta,
    word_delta_pct: pct,
  };
}
